/* eslint-disable @typescript-eslint/no-explicit-any */

import type { Metadata } from "next"
export const dynamic = 'force-dynamic'
import { notFound } from "next/navigation"
import Link from "next/link"
import Navbar from "@/components/layout/navbar"
import Footer from "@/components/layout/footer"
import { SITE } from "@/constants/site"
import { getComparisonBySlug, generateAutoComparison, determineWinners, generateUseCaseSummary } from "@/services/comparisons.service"
import ComparisonTable from "@/components/comparisons/comparison-table"
import WinnerBadge from "@/components/comparisons/winner-badge"
import ComparisonSummary from "@/components/comparisons/comparison-summary"
import SimilarComparisons from "./similar-comparisons"
import RelatedComparisons from "./related-comparisons"
import IncrementViews from "./increment-views"
import {
  ExternalLink, Star, Clock, Eye, Check, X,
  ChevronRight, Award, BarChart3, ArrowRightLeft,
} from "lucide-react"

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const slug = (await params).slug.toLowerCase()

  let comparison = await getComparisonBySlug(slug)
  if (!comparison) comparison = await generateAutoComparison(slug)
  if (!comparison) return { title: "Comparison not found" }

  const toolAName = comparison.toolA.name
  const toolBName = comparison.toolB.name
  const title = comparison.seoTitle || `${toolAName} vs ${toolBName} – Side-by-Side Comparison | LinkDit`
  const description = comparison.seoDescription || comparison.description ||
    `Compare ${toolAName} vs ${toolBName}: pricing, features, ratings, and more. Find out which AI tool is better for your needs.`
  const canonicalUrl = `${SITE.url}/compare/${slug}`

  const images: { url: string; width: number; height: number }[] = []
  if (comparison.toolA.logoUrl) images.push({ url: comparison.toolA.logoUrl, width: 200, height: 200 })
  if (comparison.toolB.logoUrl) images.push({ url: comparison.toolB.logoUrl, width: 200, height: 200 })

  return {
    title,
    description,
    metadataBase: new URL(SITE.url),
    alternates: { canonical: `/compare/${slug}` },
    openGraph: {
      title,
      description,
      type: "article",
      siteName: "LinkDit",
      locale: "en_US",
      url: canonicalUrl,
      images: images.length > 0 ? images : undefined,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: images.length > 0 ? [images[0].url] : [],
    },
  }
}

export default async function ComparisonDetailPage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const slug = (await params).slug.toLowerCase()

  let comparison = await getComparisonBySlug(slug)
  let isAutoGenerated = false

  if (!comparison) {
    comparison = await generateAutoComparison(slug)
    isAutoGenerated = true
  }

  if (!comparison) notFound()

  const { toolA, toolB } = comparison
  const winners = determineWinners(comparison)
  const useCases = generateUseCaseSummary(comparison)

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: comparison.title,
    description: comparison.description,
    url: `${SITE.url}/compare/${comparison.slug}`,
    datePublished: comparison.createdAt,
    dateModified: comparison.updatedAt,
    author: { "@type": "Organization", name: "LinkDit" },
    about: [
      { "@type": "SoftwareApplication", name: toolA.name, applicationCategory: toolA.categoryName || "AI Tool" },
      { "@type": "SoftwareApplication", name: toolB.name, applicationCategory: toolB.categoryName || "AI Tool" },
    ],
    mainEntityOfPage: { "@type": "WebPage", "@id": `${SITE.url}/compare/${comparison.slug}` },
  }

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: `Which is better, ${toolA.name} or ${toolB.name}?`,
        acceptedAnswer: {
          "@type": "Answer",
          text: winners.find(w => w.section === "ratings")?.reason || `Compare ${toolA.name} and ${toolB.name} based on features, pricing, and ratings to find the best fit for your needs.`,
        },
      },
      {
        "@type": "Question",
        name: `What is the difference between ${toolA.name} and ${toolB.name}?`,
        acceptedAnswer: {
          "@type": "Answer",
          text: `${toolA.name} and ${toolB.name} differ in pricing, features, and capabilities. ${toolA.name} has a rating of ${toolA.rating}/5 (${toolA.pricing}) while ${toolB.name} has a rating of ${toolB.rating}/5 (${toolB.pricing}).`,
        },
      },
    ],
  }

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: `${SITE.url}/` },
      { "@type": "ListItem", position: 2, name: "Compare", item: `${SITE.url}/compare` },
      { "@type": "ListItem", position: 3, name: comparison.title, item: `${SITE.url}/compare/${comparison.slug}` },
    ],
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <Navbar />
      <IncrementViews
        comparisonId={comparison.id}
        slug={comparison.slug}
        title={comparison.title}
        toolAName={toolA.name}
        toolBName={toolB.name}
      />
      <main className="flex-1">
        <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
          <Breadcrumb slug={comparison.slug} title={comparison.title} />

          <HeroSection comparison={comparison} toolA={toolA} toolB={toolB} />

          {isAutoGenerated && (
            <div className="mt-4 rounded-2xl border border-blue-100 bg-blue-50/50 px-5 py-3 text-sm text-blue-700">
              This comparison was automatically generated. Results may vary. For a detailed comparison,{' '}
              <Link href="/submit-tool" className="font-medium underline hover:text-blue-800">
                submit your own comparison
              </Link>.
            </div>
          )}

          <QuickStatsSection toolA={toolA} toolB={toolB} />

          <WinnersSection winners={winners} toolA={toolA} toolB={toolB} />

          <div className="mt-10">
            <ComparisonTable
              features={comparison.featuresComparison}
              pricing={comparison.pricingComparison}
              ratings={comparison.ratingsComparison}
              toolAName={toolA.name}
              toolBName={toolB.name}
              toolA={{ pricing: toolA.pricing, rating: toolA.rating, reviewCount: toolA.reviewCount }}
              toolB={{ pricing: toolB.pricing, rating: toolB.rating, reviewCount: toolB.reviewCount }}
              createdAt={comparison.createdAt}
              updatedAt={comparison.updatedAt}
              toolAFeatures={toolA.features}
              toolBFeatures={toolB.features}
            />
          </div>

          <ProsConsSection toolA={toolA} toolB={toolB} prosA={comparison.prosA} prosB={comparison.prosB} consA={comparison.consA} consB={comparison.consB} />

          {comparison.toolANotes && <NotesSection title={`About ${toolA.name}`} text={comparison.toolANotes} />}
          {comparison.toolBNotes && <NotesSection title={`About ${toolB.name}`} text={comparison.toolBNotes} />}

          <ComparisonSummary toolA={toolA} toolB={toolB} useCases={useCases} winners={winners} />

          {!isAutoGenerated && (
            <div className="mt-12">
              <SimilarComparisons currentId={comparison.id} categoryId={comparison.categoryId} />
            </div>
          )}

          <div className="mt-8">
            <RelatedComparisons
              currentSlug={comparison.slug}
              toolAId={toolA.id}
              toolBId={toolB.id}
            />
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}

function Breadcrumb({ title }: { slug: string; title: string }) {
  return (
    <nav className="mb-6 text-sm text-muted-foreground" aria-label="Breadcrumb">
      <ol className="flex items-center gap-1.5 flex-wrap">
        <li><Link href="/" className="hover:text-foreground transition-colors">Home</Link></li>
        <ChevronRight className="h-3.5 w-3.5 text-muted-foreground/50" aria-hidden="true" />
        <li><Link href="/compare" className="hover:text-foreground transition-colors">Compare</Link></li>
        <ChevronRight className="h-3.5 w-3.5 text-muted-foreground/50" aria-hidden="true" />
        <li className="text-foreground font-medium truncate max-w-[200px] sm:max-w-none" aria-current="page">{title}</li>
      </ol>
    </nav>
  )
}

function HeroSection({ comparison, toolA, toolB }: { comparison: any; toolA: any; toolB: any }) {
  return (
    <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-blue-50 via-white to-indigo-50 border border-blue-100/50 p-6 sm:p-10">
      <div className="absolute top-0 right-0 w-72 h-72 bg-gradient-to-bl from-blue-200/20 to-transparent rounded-full blur-3xl" />
      <div className="absolute bottom-0 left-0 w-48 h-48 bg-gradient-to-tr from-indigo-200/20 to-transparent rounded-full blur-3xl" />
      <div className="relative">
        <div className="flex flex-col sm:flex-row sm:items-center gap-4 sm:gap-6">
          <div className="flex items-center gap-4 sm:gap-6">
            <LogoAvatar src={toolA.logoUrl} name={toolA.name} size="lg" />
            <div className="flex flex-col items-center gap-1">
              <span className="text-xs font-medium text-muted-foreground">vs</span>
              <ArrowRightLeft className="h-5 w-5 text-muted-foreground/60" aria-hidden="true" />
              <span className="text-xs font-medium text-muted-foreground">vs</span>
            </div>
            <LogoAvatar src={toolB.logoUrl} name={toolB.name} size="lg" />
          </div>
          <div className="sm:ml-2">
            <h1 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-foreground">
              {comparison.title}
            </h1>
            {comparison.description && (
              <p className="mt-2 text-base text-muted-foreground max-w-2xl">
                {comparison.description}
              </p>
            )}
          </div>
        </div>
        <div className="mt-4 flex flex-wrap items-center gap-3 text-sm text-muted-foreground">
          <div className="flex items-center gap-1">
            <Eye className="h-4 w-4" aria-hidden="true" />
            {comparison.views} views
          </div>
          {comparison.categoryName && (
            <>
              <span aria-hidden="true">&middot;</span>
              <span className="rounded-md bg-primary/5 px-2.5 py-0.5 font-medium text-primary text-xs">
                {comparison.categoryName}
              </span>
            </>
          )}
          {comparison.isFeatured && (
            <>
              <span aria-hidden="true">&middot;</span>
              <span className="rounded-full bg-amber-50 px-2.5 py-0.5 text-xs font-medium text-amber-700">
                Featured
              </span>
            </>
          )}
          <span aria-hidden="true">&middot;</span>
          <div className="flex items-center gap-1">
            <Clock className="h-3.5 w-3.5" aria-hidden="true" />
            <span>
              Updated {new Date(comparison.updatedAt).toLocaleDateString("en-US", {
                month: "short", day: "numeric", year: "numeric",
              })}
            </span>
          </div>
          {comparison.status === "auto" && (
            <>
              <span aria-hidden="true">&middot;</span>
              <span className="rounded-full bg-blue-50 px-2.5 py-0.5 text-xs font-medium text-blue-600">
                Auto-generated
              </span>
            </>
          )}
        </div>
      </div>
    </div>
  )
}

function LogoAvatar({ src, name, size = "md" }: { src: string | null; name: string; size?: "sm" | "md" | "lg" }) {
  const sizeClasses = size === "lg" ? "h-16 w-16 sm:h-20 sm:w-20 text-xl sm:text-2xl" : size === "sm" ? "h-8 w-8 text-xs" : "h-10 w-10 text-sm"
  return (
    <div className={`flex shrink-0 items-center justify-center rounded-2xl bg-white text-lg font-bold text-primary overflow-hidden ring-1 ring-border/50 shadow-soft ${sizeClasses}`}>
      {src ? (
        <img src={src} alt={`${name} logo`} className="h-full w-full object-cover" />
      ) : (
        name.charAt(0)
      )}
    </div>
  )
}

function QuickStatsSection({ toolA, toolB }: { toolA: any; toolB: any }) {
  return (
    <div className="mt-8 grid gap-4 sm:grid-cols-2">
      {[toolA, toolB].map((tool, i) => (
        <div key={i} className="group relative overflow-hidden rounded-2xl border border-border/80 bg-background p-6 shadow-soft transition-all duration-200 hover:shadow-premium hover:border-primary/20">
          <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-bl from-primary/[0.03] to-transparent rounded-full blur-2xl" />
          <div className="relative">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <LogoAvatar src={tool.logoUrl} name={tool.name} />
                <div>
                  <h2 className="text-lg font-semibold text-foreground">{tool.name}</h2>
                  {tool.categoryName && (
                    <p className="text-xs text-muted-foreground">{tool.categoryName}</p>
                  )}
                </div>
              </div>
              <span className="rounded-lg bg-primary/5 px-2.5 py-1 text-xs font-semibold text-primary">
                {tool.pricing}
              </span>
            </div>
            <div className="mt-4 flex items-center gap-4">
              <div className="flex items-center gap-1.5">
                <Star className="h-5 w-5 fill-amber-400 text-amber-400" />
                <span className="text-xl font-bold text-foreground">{tool.rating.toFixed(1)}</span>
                <span className="text-xs text-muted-foreground">/5</span>
              </div>
              {tool.reviewCount > 0 && (
                <span className="text-xs text-muted-foreground">({tool.reviewCount.toLocaleString()} reviews)</span>
              )}
            </div>
            <p className="mt-3 line-clamp-2 text-sm text-muted-foreground leading-relaxed">{tool.description}</p>
            {tool.platforms && tool.platforms.length > 0 && (
              <div className="mt-3 flex flex-wrap gap-1.5">
                {tool.platforms.map((p: string) => (
                  <span key={p} className="rounded-md bg-muted/70 px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
                    {p}
                  </span>
                ))}
              </div>
            )}
            <a
              href={tool.websiteUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="btn-primary mt-4 !w-full !justify-center text-sm"
            >
              <ExternalLink className="h-3.5 w-3.5" />
              Visit {tool.name}
            </a>
          </div>
        </div>
      ))}
    </div>
  )
}

function WinnersSection({ winners, toolA, toolB }: { winners: any[]; toolA: any; toolB: any }) {
  if (winners.length === 0) return null
  return (
    <div className="mt-8">
      <div className="flex items-center gap-2 mb-4">
        <Award className="h-5 w-5 text-amber-500" />
        <h2 className="text-xl font-semibold text-foreground">Winner Highlights</h2>
      </div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {winners.map((w, i) => (
          <WinnerBadge
            key={w.section}
            winner={w.winner}
            label={w.label}
            reason={w.reason}
            toolAName={toolA.name}
            toolBName={toolB.name}
            index={i}
          />
        ))}
      </div>
    </div>
  )
}

function ProsConsSection({ toolA, toolB, prosA, prosB, consA, consB }: {
  toolA: any; toolB: any; prosA: string[]; prosB: string[]; consA: string[]; consB: string[];
}) {
  if (prosA.length === 0 && prosB.length === 0 && consA.length === 0 && consB.length === 0) return null

  return (
    <div className="mt-10">
      <h2 className="text-xl font-semibold text-foreground flex items-center gap-2">
        <BarChart3 className="h-5 w-5 text-muted-foreground" />
        Pros & Cons
      </h2>
      <div className="mt-4 grid gap-6 sm:grid-cols-2">
        <ProConCard tool={toolA} pros={prosA} cons={consA} />
        <ProConCard tool={toolB} pros={prosB} cons={consB} />
      </div>
    </div>
  )
}

function ProConCard({ tool, pros, cons }: { tool: any; pros: string[]; cons: string[] }) {
  return (
    <div className="rounded-2xl border border-border/80 bg-background p-6 shadow-soft">
      <div className="flex items-center gap-3 mb-4">
        <LogoAvatar src={tool.logoUrl} name={tool.name} size="sm" />
        <h3 className="text-lg font-semibold text-foreground">{tool.name}</h3>
      </div>
      {pros.length > 0 && (
        <div className="mt-3">
          <p className="text-sm font-medium text-emerald-600 flex items-center gap-1.5 mb-2">
            <Check className="h-4 w-4" /> Pros
          </p>
          <ul className="space-y-2" role="list">
            {pros.map((p, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                <Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500" />
                {p}
              </li>
            ))}
          </ul>
        </div>
      )}
      {cons.length > 0 && (
        <div className="mt-4">
          <p className="text-sm font-medium text-red-600 flex items-center gap-1.5 mb-2">
            <X className="h-4 w-4" /> Cons
          </p>
          <ul className="space-y-2" role="list">
            {cons.map((c, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                <X className="mt-0.5 h-4 w-4 shrink-0 text-red-400" />
                {c}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

function NotesSection({ title, text }: { title: string; text: string }) {
  return (
    <div className="mt-8 rounded-2xl border border-border/80 bg-background p-6 shadow-soft">
      <h3 className="text-sm font-semibold text-foreground">{title}</h3>
      <p className="mt-2 text-sm text-muted-foreground leading-relaxed">{text}</p>
    </div>
  )
}
